# Generated by Django 4.0.1 on 2024-11-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_blog_blogvisit_inquiry_partner_alter_faq_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
